---
- hosts: default
  become: true
  tasks:
    - file:
        path: /var/todolist-back-end
        state: directory
        mode: 0755

    - copy:
        src: /var/lib/jenkins/workspace/todolist-back-end/scripts/
        dest: /var/todolist-back-end

    - name: start all containers
      shell: |
        cd /var/todolist-back-end
        docker-compose up -d