---
- hosts: default
  become: true
  tasks:
    - file:
        path: /var/todolist-back-end
        state: directory
        mode: 0755
    - copy:
        src: /var/lib/jenkins/workspace/todolist-back-end/scripts/
        dest: /var/todolist-back-end

    - file:
        path: /var/todolist-back-end/db_config.sh
        mode: 0755

    - name: DB migration
      shell: /var/todolist-back-end/db_config.sh

    - stat:
        path: /var/todolist-back-end/todo-list-api-1.0-SNAPSHOT.jar
      register: old_package

    - name: delete old project package
      file:
        path: /var/todolist-back-end/todo-list-api-1.0-SNAPSHOT.jar
        state: absent
      when: old_package.stat.exists

    - copy:
        src: /var/lib/jenkins/workspace/todolist-back-end/target/todo-list-api-1.0-SNAPSHOT.jar
        dest: /var/todolist-back-end

    - copy:
        src: /var/lib/jenkins/workspace/todolist-back-end/my_supervisor.conf
        dest: /etc/supervisor/conf.d

    - file:
        path: /var/todolist-back-end/check_mysql.sh
        mode: 0755

    - name: add default hosts of mysql
      lineinfile:
        dest: /etc/hosts
        regexp: ''
        state: present
        insertafter: EOF
        line: '192.168.30.15  mysql_machine'
