pipeline{
  agent any

  stages{

    stage('Test') {
      steps{
        sh 'mvn test'
      }
    }

    stage('Build'){
      steps{
        sh '/var/lib/jenkins/workspace/todolist-back-end/scripts/publish.sh'
      }
    }
  }
}