pipeline{
  agent any

  stages{

    stage('Test') {
      steps{
        sh 'mvn test'
      }
    }

    stage('Build'){
      steps{
        sh '/var/lib/jenkins/workspace/todolist-back-end/scripts/publish.sh'
      }
    }

    stage('Deploy'){
      steps{
        sh 'ansible-playbook /var/lib/jenkins/workspace/todolist-back-end/scripts/deploy-with-docker.yml --extra-vars="ansible_become_pass=remote"'
      }
    }
  }
}